# Generated by Django 5.1.3 on 2024-11-25 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='volumen',
            field=models.IntegerField(default=0),
        ),
    ]
